set hidden
set nobackup
set tabstop=2
set shiftwidth=2
set expandtab
set conceallevel=1
set cursorline
set updatetime=300
set encoding=UTF-8
set mouse=a
set number
set mouse=a
set whichwrap+=<,>,[,]
"" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase
set fileformats=unix,dos,mac
syntax enable 
